prefix_name = "twitter"
region = "East US"
resource_group_name = "resource-group-twitter"
acr_id = "/subscriptions/9752f840-f2b4-4863-95ef-d17133404ce4/resourceGroups/resource-group-twitter/providers/Microsoft.ContainerRegistry/registries/acrTwitter"
resource_group_location = "East US"